本アプリのREADMEを作成する
KyusokLee/CodeAssignment_MVVM_Combine pull request #12
Opened 2024-06-17 10:44 UTC by KyusokLee

2024-07-02 01:39 UTC, Ogijun2018 requested changes

2024-07-02 01:39 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> -
この差分いらないのでもし消せたら消しておいてくれると嬉しいっす 🙏

2024-07-02 02:53 UTC, Ogijun2018 commented on README.md
> +```
多分これ上の章のものなのでいらないと思う！

2024-07-02 02:53 UTC, Ogijun2018 commented on README.md
> +- 本アプリは`GitHub Rest API`の中、検索用のエンドポイントと星付けー・解除用のエンドポイントを使用しています。検索用の`strcut`である`GitHubSearchRepositoriesRequest`と星付けー・解除用である`GitHubStarRepositoriesRequest`はそれぞれ異なるリクエストを処理しているが、ジェネリックとプロトコルを用いることでコード
```suggestion
- 本アプリは`GitHub Rest API`の中、検索用のエンドポイントと星付け・解除用のエンドポイントを使用しています。検索用の`struct`である`GitHubSearchRepositoriesRequest`と星付け・解除用である`GitHubStarRepositoriesRequest`はそれぞれ異なるリクエストを処理しているが、ジェネリックとプロトコルを用いることでコードの再利用性を増やすことができます。
```

2024-07-02 02:53 UTC, Ogijun2018 commented on README.md
> +- 本アプリは`GitHub Rest API`の中、検索用のエンドポイントと星付けー・解除用のエンドポイントを使用しています。検索用の`strcut`である`GitHubSearchRepositoriesRequest`と星付けー・解除用である`GitHubStarRepositoriesRequest`はそれぞれ異なるリクエストを処理しているが、ジェネリックとプロトコルを用いることでコード
（日本語についての指摘）
一文の中で「です。ます。」で終わるのと、「だ。である。が。」で終わる文体が統一されてないと日本語としてはちょっと不自然な感じがするね。

> それぞれ異なるリクエストを処理しているが

の部分は

> それぞれ異なるリクエストを処理していますが

の方が自然。

参考: https://note.com/akira_e_noway/n/n767a2acf131c

2024-07-02 02:53 UTC, Ogijun2018 commented on README.md
> +```
ちょうど対応してもらってた

2024-07-02 03:41 UTC, KyusokLee commented on README.md
> +- 本アプリは`GitHub Rest API`の中、検索用のエンドポイントと星付けー・解除用のエンドポイントを使用しています。検索用の`strcut`である`GitHubSearchRepositoriesRequest`と星付けー・解除用である`GitHubStarRepositoriesRequest`はそれぞれ異なるリクエストを処理しているが、ジェネリックとプロトコルを用いることでコード
ご指摘、ありがとうございます！
[266dc1a](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/12/commits/266dc1a3f0da96dee4ed296c215e98bc4e19ab51)にて修正しました。ご確認お願いします！

2024-07-02 04:24 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> -
ちょっとRevertの作業初めてなので、ログが汚くなっています笑、、
[e533365](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/12/commits/e5333655f65a18c53b58b721b296b7aad407d48c)にてコード修正しました。ご確認お願いします！

2024-07-03 01:16 UTC, Ogijun2018 requested changes

2024-07-03 01:16 UTC, Ogijun2018 commented on README.md
> +## 🔥 Trouble Shooting
ここの章は不要なら消しちゃった方が良さそう？

2024-07-03 03:20 UTC, KyusokLee commented on README.md
> +## 🔥 Trouble Shooting
[742629e](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/12/commits/742629e390e12cdf6630fe5f0c4d3030c33ee7cd)にて不要な箇所を削除しました！ご確認お願いします！

2024-07-05 04:29 UTC, merged