Combineを用いて、GET リクエストを送るボタン生成
KyusokLee/CodeAssignment_MVVM_Combine pull request #3
Opened 2024-05-07 10:13 UTC by KyusokLee

## 何故やるのか
- MVVMアーキテクチャとCombineの使い方を習い、データフローやリアクティブプログラミングの理解を深めるためである
- 今後、APIを叩いてうまくデータ処理をするために、まずは簡単に背景色を変えるコードを書いた

## 変更点
- `HomeViewController`の`getAPIButton`をタップすると、背景色が青く変わる
- `HomeViewModel`を定義し、画面と表示される画面上のイベント処理を分離する

## 期待される結果
- `getAPIButton`をタップすると、`getAPIButton`の`backgroundColor`が青くなる

## 動作確認方法
- スクショ

## 特に見てほしい点
- `HomeViewModel`で定義したSubjectは正しいか
- `HomeViewController`の`setupObservers`の中、`sink`や`store`メソッドを正しく書いているか

## スクリーンショット・録画（あれば）
<img src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/89962765/ce4c893a-26cc-48ea-8278-c7fd708de560" width=30%>

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
>          setupConstraints()
methodの切り方がちょっとイマイチかも。
もう少し意味のまとまりで区切っておいた方が良さそう。
例えば、
AutoLayoutを使うのであれば、addSubViewして、Constraintを設定は一つのまとまりの処理として扱っておいた方がリーディングでも意味のまとまりという点でもわかりやすいかな。

setUpControllerというのもやっぱり何をしたいメソッドなのかわからないかも。

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
>          setupConstraints()
例えば自分が分けるのであれば、
setViews()
setupObservers()

の二つをViewDidLoadで呼んであげる。
setViewsはViewに関する設定なので、
この中でaddSubViews、Constraintの設定、backgroundColorの調整

setupObserves()の中で
combineで流れてきたものをsinkする。
みたいに分けるかな。

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    private func setupObservers() {
命名に関しては、別に悪くはないけど一般的には
bindとかsubscribe(購読)みたいな関数名がいわゆるReactiveなプログラミングの中では使われることが多いかも！

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        viewModel.getAPIButtonColorSubject.sink { [weak self] buttonColor in
Combineによって流れてくる値はmainスレッドで流れてくるかそれ以外のスレッドで流れてくるかわからないので、ここはmain threadで受け取るようにしておく方が安全。
https://developer.apple.com/documentation/combine/publisher/receive(on:options:)

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        viewModel.getAPIButtonColorSubject.sink { [weak self] buttonColor in
アプリ開発においては、UIの更新はメインスレッドで行う必要があります
https://zenn.dev/kamimi01/scraps/01848d0c75eada

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/Home/HomeViewModel.swift
> +        getAPIButtonColorSubject.send(UIColor.systemBackground)
今の使われ方をするのであれば、
[PassthroughSubject](https://developer.apple.com/documentation/combine/passthroughsubject)というよりも[CurrentValueSubject](https://developer.apple.com/documentation/combine/currentvaluesubject)でもいいかも。

2024-05-07 10:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/Home/HomeViewModel.swift
> +        getAPIButtonColorSubject.send(UIColor.systemBackground)
ここの使い分けは難しいんだけど、ただ値が送られるというよりもボタンの色というStateをVMが保持しているって考えだとCurrentValueSubjectの方が適切なんじゃないかな
https://www.avanderlee.com/combine/passthroughsubject-currentvaluesubject-explained/

https://zenn.dev/yorifuji/articles/ios-swift-combine#passthroughsubject

2024-05-08 06:34 UTC, tosh7 approved these changes

2024-05-08 06:34 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/Home/HomeViewModel.swift
> +    var getAPIButtonColor = CurrentValueSubject<UIColor, Never>.init(.systemBackground)
細かいことを言うと、あんまりSwiftでこういうinitの使い方は見かけないから
```
var getAPIButtonColor: CurrentValueSubject<UIColor, Never> = .init(.systemBackground)
```
とか
```
var getAPIButtonColor = CurrentValueSubject<UIColor, Never>(.systemBackground)
```
とかの方がSwiftっぽい書き方になるかな。
今の書き方でもコンパイラの解釈としては問題はないです

2024-05-08 10:19 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/Home/HomeViewModel.swift
> +    var getAPIButtonColor = CurrentValueSubject<UIColor, Never>.init(.systemBackground)
@tosh7 
フィードバックありがとうございます！
教えてくださった内容、確認しました！今後から活用させていただきます！

2024-05-09 01:41 UTC, Ogijun2018 requested changes

2024-05-09 01:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    /// store:
これは見やすくするためのtipsなんだけど、`///` のdoc-commentをつける理由は主にoptionを押しながらfuncや変数をクリックしたときのdescriptionのためにあります。
現状のこのコメントの書き方だと、↓のような感じになるんだけど
<img width="580" alt="スクリーンショット 2024-05-09 10 34 23" src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/feaa58d1-fc59-4d55-a76f-288d1cfcb053">

ここを提案のように書き換えると、こんな感じに表示が綺麗になります！
<img width="567" alt="スクリーンショット 2024-05-09 10 38 32" src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/85014be0-2b51-4924-adb3-ecaf89a3c251">

```suggestion
    /** ViewModelなどViewController側で常に監視しておくべき対象を、セットアップする関数。イベント発生時に正常にデータバインドをするために、Observerを設定する感じ

    - `sink:` Publisherからのイベントを購読する.  つまり、イベントを受信したときの処理を指定できる。
    - `receive(on:):` イベントを受け取るスレッドを指定する
    - `store:` hogehoge:
    */
```

ここらへんの見やすくするテクニックはまとめてくれてる人がいるのでチェックしてみるとよさそう。
https://qiita.com/ashdik/items/0019b6ba5ed228d41e66

2024-05-09 01:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
>          /// UIActionのclosureを用いて関数を呼び出す
`///` はdoc-commentなので、ここみたいな感じで変数や関数の説明じゃなくコードの説明をしている場合は通常コメントの `//` でいいかな！
ここの使い分けは知っておいて損はしないと思う！

2024-05-09 02:17 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    /// store:
@Ogijun2018 
フィードバックありがとうございます！コード修正します！今後活用させていただきます❤️

2024-05-10 02:43 UTC, tosh7 commented
VMの作成とAPI Clientの作成はPR分けてもよかったかもね？

2024-05-10 02:46 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    private var repositories = [Repository]()
これは、StateなのでVCではなくVMに持たせておいてVCが必要なタイミングでVMへと参照しに行く形にしたいですね。

2024-05-10 04:10 UTC, Ogijun2018 commented
> VMの作成とAPI Clientの作成はPR分けてもよかったかもね？

ですね、ちょっとここは自分のミス

2024-05-10 08:10 UTC, Ogijun2018 commented
@KyusokLee 

> HomeViewControllerのgetAPIButtonをタップすると、背景色が青く変わる

descriptionに書いてあるけど、最新の状態だと青く変わらないで合ってますかね？
もし変更していたらdescriptionの方も変更しておいてほしいです！

2024-05-10 08:54 UTC, Ogijun2018 requested changes

2024-05-10 08:54 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +                guard let self = self else { return }
```suggestion
                guard let self else { return }
```
Swift 5.7から↑のように書けるようになってます
https://github.com/apple/swift-evolution/blob/main/proposals/0345-if-let-shorthand.md

2024-05-10 08:54 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/Home/HomeViewModel.swift
> +                self.repositoriesSubject.send(repositories)
APIから返ってきたレスポンスを `Repositories: Codable` に変換して、そのRepositoriesをそのままViewControllerに渡している（repositoriesSubjectに入れてる）と思うんだけど、ViewControllerに渡す用のModelを新しく作ってしまった方が綺麗にいくかなと思いました！

一旦Repositories/Repository/RepositoryUserは `decoder.keyDecodingStrategy = .convertFromSnakeCase` で自動的に変換されるstructの中身にしておいて、新しく↓みたいなViewControllerで表示する用のModelを作ってみると

```
struct RepositoriesForView {
  let repositoryCount: Int?
  let items: [RepositoryForView]
}
```

ViewModelの28行目で `self.repositoriesForView = .init(repositoryCount: model?.totalCount, items: model?.items)`
みたいにできて、

```
// JSONDecoderのkeyDecodingStrategyの設定で、snake caseをcamelCaseにすることも可能だったが、今回はもっとわかりやすい変数名にしたいため、以下のようにCoding keysを使った。
```

の部分の問題も解決できそう。

2024-05-10 10:42 UTC, Ogijun2018 requested changes

2024-05-10 10:42 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Extensions/Error/ErrorType+Utils.swift
> +            return "知られていないエラー "
`unknownError` は日本語的にあんまり「知られていない」とは言わないかも。「不明なエラー」とかがよく使われるかな。

2024-05-10 10:42 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Extensions/Error/ErrorType+Utils.swift
> +            return "データを正しく表示できませんでした。\nもう一度、お試しください。"
デコードエラーは表示のエラーというよりは型変換のエラーなので、普通に「デコードエラーが発生しました」でいい気がする。

2024-05-10 10:42 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +}
`Repository` は `Repositories` の中、 `RepositoryUser` は `Repository` の中でしか使われていないので、structは中に入れちゃった方がよさそう。

2024-05-13 07:56 UTC, Ogijun2018 requested changes

2024-05-13 07:56 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +    func request<T: GitHubAPIClientProtocol>(_ requestProtocol: T, type: GitHubAPIType, completion: @escaping(Result<Repositories?, ErrorType>) -> Void) {
`requestProtocol` はgenericでどんな型でも受け付けられるようになってるけど、completionで返っていく型が `Result<Repositories?, ErrorType>` になっているから、実質 `GitHubSearchRepositoriesRequest` しか受け付けられなくなってしまっているね。
ここも共通化するには associatedtype を使うのが良さそう。↓を参考にしてみてください！
https://qiita.com/akeome/items/78e650f27a4c53e1406a

2024-05-13 08:09 UTC, Ogijun2018 requested changes

2024-05-13 08:09 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Extensions/Error/ErrorType+Utils.swift
> +            return "不明なエラー "
```suggestion
            return "不明なエラー"
```

2024-05-13 08:09 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
ここは `[Repository]` じゃなくて `Repositories` でよさそうだね。
そうすると、 `Repository` 型は `Repositories` 型の中に入れられるはず。

2024-05-13 08:09 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +        case items
ここは keyDecodingStrategyを設定したので不要になりそうだね。

2024-05-13 08:09 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> + -  APIで定義したKeyの名前を変えたのは、ViewControllerとかでそのkeyのデータを用いるとき、わかりやすくするためである。そんため、decodingのStrategyは自動で変換されるメソッドを使うのが良さそう
ここのコメントも keyDecodingStrategy使うように変更したので消してよさそう。

2024-05-13 08:09 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +    /// decodeのkeyDecodingStrategyメソッドを用いて、converFromSnakeCaseで自動的も変換されるStructの中身にしておく
```suggestion
    /// decodeのkeyDecodingStrategyメソッドを用いて、convertFromSnakeCaseで自動的に変換されるstructの中身にしておく
```

2024-05-13 08:21 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +    func request<T: GitHubAPIClientProtocol>(_ requestProtocol: T, type: GitHubAPIType, completion: @escaping(Result<Repositories?, ErrorType>) -> Void) {
@Ogijun2018 
資料と説明、ありがとうございます！982930eにてコードを修正しました。
修正内容は、
`GitHubAPIClientProtocol`に `associatedtype`を定義し、`APIClient`の`request`メソッドで返す`Result`として受け付けたGeneric Typeの値を返すようにしました。

2024-05-13 08:23 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Extensions/Error/ErrorType+Utils.swift
> +            return "不明なエラー "
@Ogijun2018 
[229c23a]にて修正しました！

2024-05-13 08:27 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
@Ogijun2018 
[6f20105]にて修正しました！ご確認、お願いします！

2024-05-13 08:29 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +        case items
[f61cb9d]にて修正しました！ご確認、お願いします！

2024-05-13 08:32 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> + -  APIで定義したKeyの名前を変えたのは、ViewControllerとかでそのkeyのデータを用いるとき、わかりやすくするためである。そんため、decodingのStrategyは自動で変換されるメソッドを使うのが良さそう
[2cbd7a0]にて、修正しました！ご確認、お願いします！

2024-05-13 08:32 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +    /// decodeのkeyDecodingStrategyメソッドを用いて、converFromSnakeCaseで自動的も変換されるStructの中身にしておく
[2cbd7a0]にて、修正しました！ご確認、お願いします！

2024-05-13 09:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
`totalCount` は repositoriesの中にあるはずだから、わざわざ別の引数に持つ必要はなさそうだね。

2024-05-13 09:32 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
> そうすると、 Repository 型は Repositories 型の中に入れられるはず。

これの対応もお願いします！

2024-05-13 09:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
`let repositories = RepositoriesForView(totalCount: model.totalCount, repositories: model.self)` のところは、特に `model.self` とする必要はなさそう

2024-05-14 03:52 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
@Ogijun2018 
[a67b936]にてコード修正しました！ご確認、お願いします！

2024-05-14 11:10 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
@KyusokLee 
> そうすると、 Repository 型は Repositories 型の中に入れられるはず。

これが結局対応されてなさそう。。？

2024-05-14 11:30 UTC, Ogijun2018 requested changes

2024-05-14 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +struct Repositories: Codable {
一番外側に出てるstructはこの `Repositories` だと思うんだけど、ファイル名が `Repository` になってるから混乱しそうだね。 一番外のstructと合わせて `Repositories.swift` にするのがよさそう

2024-05-14 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +struct RepositoriesForView {
自分で例で書いといて言うのもアレなんだけど、 `~ForView` って命名は冗長すぎるのでさすがにやめた方がよさそう。
VC側で表示するこっちのstructは `~ForView` を消して、 Entitiesに入ってる `Repositories` の方を `RepositoriesResponse` って言うふうにするのがよさそうです！（なんしーさんアドバイス）

実は今同じような変更をリファクタリングでしています。（ https://github.com/st-tech/zozotown-ios/pull/4595 ）

2024-05-14 11:40 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +struct Repositories: Codable {
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/3#discussion_r1599860276
↑のコメントと合わせると、 ここのファイルは `RepositoriesResponse.swift` にして、 `struct RepositoriesResponse: Codable` にする。

2024-05-15 03:18 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +    init(totalCount: Int?, repositories: [Repository]) {
@Ogijun2018 
修正の漏れがありました！
[2c98915]にてコード修正しましたので、ご確認お願いします！

2024-05-15 03:30 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/Repository.swift
> +struct Repositories: Codable {
@Ogijun2018 
上記のコメントに沿って、[e7e82b9]にてコード修正しました！ご確認、お願いいたします！

2024-05-15 03:36 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +struct RepositoriesForView {
@Ogijun2018 
コメント、ありがとうございます！リファクタリング中のコードを拝見しました！
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/3#discussion_r1600897220 のコメントに合わせて、[e7e82b9]でコード修正しました！ご確認、お願いいたします！

2024-05-15 04:32 UTC, Ogijun2018 requested changes
あと少しだけ！

2024-05-15 04:32 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    private var repositoriesForView: Repositories?
ここも `ForView` は不要ですね！
```suggestion
    private var repositories: Repositories?
```

2024-05-15 04:32 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +struct Repositories {
ファイル名が `RepositoriesForView.swift` のままなので修正お願いします！

2024-05-15 04:32 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +        self.totalCount = totalCount
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/3#discussion_r1598162149
ここで言ってたのはこういうことです！

```suggestion
    init(repositories: RepositoriesResponse) {
        self.totalCount = repositories.totalCount
```

2024-05-15 05:39 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/RepositoriesForView.swift
> +        self.totalCount = totalCount
@Ogijun2018 
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/3#discussion_r1600923598
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/3#discussion_r1600924516
↑のコメントも合わせて[21c2ccc]にてコード修正しました！ご確認、お願いします！🙇

2024-05-15 08:44 UTC, tosh7 approved these changes

2024-05-15 10:02 UTC, Ogijun2018 approved these changes

2024-05-15 10:02 UTC, merged