UICollectionViewFlowLayoutを用いて動的にCollectionViewCellのサイズを計算し、リポジトリ一覧を表示する
KyusokLee/CodeAssignment_MVVM_Combine pull request #4
Opened 2024-05-15 12:40 UTC by KyusokLee

## 何故やるのか
- APIを叩いて取得したデータをUIとして表示するため
- XibファイルなしでCollectionViewとCollectionViewCellの使い方・レイアウトの設定方法を身につけるため
- UICollectionViewFlowLayoutを用いて、Cellのサイズを動的に計算して正常に表示するため

## 変更点
`UISearchController`の中に`searchBar`を設け、ユーザが打ったワードでGitHub上のリポジトリを検索できる。
APIを叩いてから取得するリポジトリのデータモデルを`RepositoriesResponse`に、Viewとして表示するためのモデルを`Repositories`に分け、`Codable`を継承する`struct`の中に不要な`CodingKeys`ロジックを消す。また、テストを容易にするため、ビューとして表示するためのモデルを容易した。

## 期待される結果
入力したワードで検索すると、検索結果が正常にデータとしてビューに表示されること。
`UICollectionViewCell`のサイズが動的に計算され、`description`が全部表示されること。

## 動作確認方法
- 録画動画

## スクリーンショット・録画（あれば）

https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/89962765/a68da29a-97d8-4467-a56e-20229394bbb5

2024-05-16 02:44 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    private var searchWord: String?
これらはState(この画面がどういう表示を行うかの状態)にあたるのでViewModelに持たせておきたいかも。

2024-05-16 02:44 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    private var searchWord: String?
例えば、repositoriesはVMに持たせておいて
```
        viewModel.repositoriesSubject
            .receive(on: DispatchQueue.main)
            .sink { [weak self] _ in
                guard let self else { return }
                self.repositoryCollectionView.reloadData()
            }
            .store(in: &cancellables)
```
のようにsinkの中ではreloadDataだけを呼べるようにできないかやってみてほしい！

2024-05-16 02:44 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    }
`searchBarSearchButtonClicked(_ searchBar: UISearchBar)`の中で、`searchBar.text: String?`で検索窓の中の文字列は取れなさそうかな？
https://developer.apple.com/documentation/uikit/uisearchbar/1624282-text
それができると、
`searchBar(_ searchBar: UISearchBar, textDidChange searchText: String)`と`self.searchWord`は不要にできるかも。

2024-05-16 02:44 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        setupLanguageNameLabelConstraints()
個人的な考え方だと、これそこまで細かくわけなくてもいいかも？
例えば、
AというLabelとBというButtonの制約を考えた時に、AのBottomとBのTopを4pt開けるという制約は、Aの制約でもあるしBの制約でもある。
ただ、ここまで細かくしてしまうとその関係性が見えづらくなってしまうというデメリットもあるかもなと思った。

2024-05-16 05:40 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    }
@tosh7 
レビューと参考資料、ありがとうございます！いただいたコメントに沿って、[b91b3bd]にてコード修正しました。
ご確認、お願いします！

2024-05-16 06:04 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    private var searchWord: String?
@tosh7 
レビューに沿って、[8767c99]にてコード修正しました！
`HomeViewModel`の`repositoriesSubject`を`CurrentValueSubject`に変更し、値を保持できるようにしました。
こうすることで、`HomeViewController`では、`viewModel.repositoriesSubject.value`へのアクセスが可能となり、`private var repositories: Repositories?`は不要になりました。

おっしゃった内容は↑のような形で間違いないでしょうか？
ご確認、お願いします！

2024-05-16 07:22 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        setupLanguageNameLabelConstraints()
@tosh7 
コメント、ありがとうございます！
おっしゃる通り、Aの制約のときにBの制約に関する内容も含まれるので、裏返してみれば、Bの制約に関する関数にもなりますね！大変勉強になりました！
[22ccaaf]にてコード修正しました！
ご確認、お願いいたします！

2024-05-17 02:22 UTC, Ogijun2018 reviewed
動作確認した感じ、作者の画像のところは表示されてないけど一旦これで進めちゃって大丈夫かな？

2024-05-17 02:59 UTC, Ogijun2018 commented
リポジトリ名が長い時にはみ出ちゃってるね

![Simulator Screenshot - iPhone 15 Pro - 2024-05-17 at 11 58 32](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/a86493d8-8819-4a6e-a19d-4528b72bf2f3)

2024-05-17 03:12 UTC, Ogijun2018 commented
これは見え方の問題だからそんなに頑張る必要はないんだけど、collectionViewは画面いっぱいまであった上で中のセル部分で余白を作ってあげた方がそれっぽく見えると思う。

<img src=https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/b0ecdd07-a4da-48fc-968c-58630442e07c  width=50%>

雑だけど↓こんな感じ。（背景の赤色がcollectionView、青い部分がcell.contentView）

<img src=https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/ddbd92fb-ae23-49ba-a93c-02a961a81728  width=50%>

こうするとcornerRadiusの設定がめんどくさいことになるかもしれないけど、大変だったらcornerRadiusつけなくてもOK

2024-05-17 05:34 UTC, KyusokLee commented
@Ogijun2018 
[9526f07]でリポジトリ名やユーザ名が長いときに、`nameLabel`と`userAccessoryView`がはみ出る現象を修正しました！
ご確認、お願いします！

2024-05-17 05:49 UTC, Ogijun2018 commented
> 動作確認した感じ、作者の画像のところは表示されてないけど一旦これで進めちゃって大丈夫かな？
> → error: Image url is blacklisted って返ってきてるから、意図するものではなさそう

こちらはnetskopeによって制限がかかってしまい、netskopeをオンにしていると画像が表示されない。
netskopeをオフにすると表示されたので、既存のコードのままで大丈夫そう。

2024-05-17 06:30 UTC, KyusokLee commented
@Ogijun2018 
[c0a4528]にて以下のようにコードを修正しました。
`repositoryCollectionView`の`layout`を既存の`flowlayout`から`UICollectionLayoutListConfigurartion(appearance: .insetGrouped)`に変更することで、collectionViewを画面いっぱいにでき、最初と最後のCellの部分だけ丸くすることができる。
また、`RepositoryCollectionViewCell`を既存の`UICollectionViewCellタイプから`UICollectionViewListCell`に変更し、`UICellAccessory`を用いて、各cellの右の部分に矢印→を表示するようにした。`cell.accessories = .disclosureIndicator()`

ご確認、お願いします！

2024-05-17 06:34 UTC, Ogijun2018 requested changes

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Resources/Info.plist
> +	</dict>
これなくてもnetskopeオフにした状態なら画像みられるから、特に必要なさそう

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Apps/AppDelegate.swift
> +        }
ここってなんか意図的にやりたいことがあったって感じかな？
今の挙動だと特にこれがあってもなくても見え方変わらないんじゃないかなと思い。
もしリポジトリ詳細画面へ遷移したときの見え方を変えたいため、とかの場合だったらこのPRではこの変更は入れず、Step3のPRを出すときに追加で良さそう。

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.flowLayout)
ZOZOTOWNのコードの中では `self` は基本的につける必要がないときはつけないようにしてるので、flowLayoutだけで大丈夫そう

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        setupRepositoryCollectionViewConstraints()
このfuncっているのかな…もう直接ここに `setupRepositoryCollectionViewConstraints` の中身を入れちゃっていいんじゃないかな？

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +    }
何もしてないなら特に置いておく必要はなさそう

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +                "X-GitHub-Api-Version" : "2022-11-28"
これって必要？

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
三項演算子使えばこんな感じに1文で書ける

```suggestion
        number >= 10000 ? String(format: "%.1f万", Double(number) / 10000) : String(number)
```

2024-05-17 06:34 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
プラスで、今回1万を超えたらformatするっていう基準を作ってfuncの中に `10000` っていう数字を入れていると思うんだけど、こういう時は↓みたいにConstで名前を定義してあげると、なんで10000なのか、何の10000なのかがわかりやすくなる。

```
private enum Const {
   /// 数値を短縮表示する基準
   static let numberFormatThreshold: Int = 10000
}
```
```suggestion
       number >= Const.numberFormatThreshold ? String(format: "%.1f万", Double(number) / Const.numberFormatThreshold) : String(number)
```

2024-05-17 06:39 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Resources/Info.plist
> +	</dict>
[78016ba]にて修正しました！ご確認、お願いします！

2024-05-17 06:41 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Apps/AppDelegate.swift
> +        }
[9aa5fbb]にてコード修正しました！ご確認、お願いします！

2024-05-17 06:45 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.flowLayout)
[c655fd3]にて修正しました！ご確認、お願いします！

2024-05-17 06:47 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        setupRepositoryCollectionViewConstraints()
[0228a38]で修正しました！ご確認、お願いします！

2024-05-17 06:52 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +                "X-GitHub-Api-Version" : "2022-11-28"
[8313a57]にてhttps://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604394407 
 の内容も含めて、コード修正しました。ご確認、お願いします！

2024-05-17 07:00 UTC, Ogijun2018 requested changes

2024-05-17 07:00 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.top.equalTo(nameLabel.snp.bottom).offset(15)
`constraint.bottom.equalTo(descriptionLabel.snp.top).offset(-15)` ですでに「nameLabelとdescriptionLabelの間隔は15ptである」っていうのは宣言されているから、このコードは同じことを言ってるだけだから必要ないですね。

2024-05-17 07:00 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.top.equalTo(descriptionLabel.snp.bottom).offset(15)
これも `constraint.bottom.equalTo(userAccessoryView.snp.top).offset(-15)` と重複しているから不要。

2024-05-17 07:00 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.leading.equalTo(userImageView.snp.trailing).offset(10)
`constraint.trailing.equalTo(userNameLabel.snp.leading).offset(-10)` と重複してるから不要そう

2024-05-17 07:00 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.leading.equalTo(languageColorView.snp.trailing).offset(5)
`constraint.trailing.equalTo(languageNameLabel.snp.leading).offset(-5)` と重複しているから不要そう

2024-05-17 07:02 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
[b6e1f6b]にてコード修正しました！ご確認、お願いします！

2024-05-17 07:03 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        viewModel.search(queryString: searchBar.text ?? "")
このロジックだと、VMでの使われ方も見ていると空文字で検索されるケースもあるかも？

2024-05-17 07:03 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            userImageView.sd_setImage(with: url, placeholderImage: defaultImage) { [weak self] (image, error, cacheType, url) in
cacheTypeのようにクロージャー内で使用しない値は`_`で書くことができるよ！
```suggestion
            userImageView.sd_setImage(with: url, placeholderImage: defaultImage) { [weak self] image, error, _, _ in
```

2024-05-17 07:03 UTC, tosh7 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +                if let error = error {
```suggestion
                if let error {
```

2024-05-17 07:04 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Resources/Info.plist
> +	</dict>
特に変える必要がないならInfo.plist自体の変更は無くした方がいいね。今まだFiles ChangedにInfo.plistが含まれているから、無くして欲しいです！

2024-05-17 07:05 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
イメージ的にはCellのファイルの中にConstを置く感じだったけど、まあこれでもいいか

2024-05-17 08:10 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.leading.equalTo(languageColorView.snp.trailing).offset(5)
[5b029de]にて以下のコメントでレビューしていただいた箇所のコードを修正しました。
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604431834
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604432973
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604437588
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604438133

ご確認、お願いします！

2024-05-17 08:24 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        viewModel.search(queryString: searchBar.text ?? "")
@tosh7 
[6d1f480]にて、コード修正しました！ご確認、お願いします！

2024-05-17 08:26 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            userImageView.sd_setImage(with: url, placeholderImage: defaultImage) { [weak self] (image, error, cacheType, url) in
@tosh7 
[cae3d63]にて、コード修正しました！ご確認、お願いします！

2024-05-17 08:27 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +                if let error = error {
[63b5a80]でコード修正しました！ご確認、お願いします！

2024-05-17 09:10 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.flowLayout)
doc-commentの `/// FlowLayout` 修正必要だね。 変数名普通に `layout` だけでもいいかな。

2024-05-17 09:23 UTC, Ogijun2018 requested changes

2024-05-17 09:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +//}
いらないコメントアウトは消しておきましょう

2024-05-17 09:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//            .withTintColor(.systemGray5, renderingMode: .alwaysOriginal)
いらなければ消しておきましょう

2024-05-17 09:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//            constraint.bottom.equalTo(contentView.snp.bottom).offset(-8)
いらないコメントは消しておきましょう

2024-05-17 09:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +     - 今後、RepositoriesForViewのModelのデータに基づいて、Cellのデータを確立させる
このコメントは消しても良さそう？

2024-05-17 09:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +                self.userImageView.image = image
この処理の仕方だと、errorだった場合は `self.userImageView.image = defaultImage` が入った後に `self.userImageView.image = image` が行われてしまい、nilに書き変わってしまうね

2024-05-17 10:10 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +                self.userImageView.image = image
@Ogijun2018 
[19cbc56]にて以下のコメントでレビューしていただいた箇所のコードを修正しました。
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604611952
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604612557
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604613395
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1604615764

お手すきの際にご確認、お願いします！

2024-05-20 08:02 UTC, Ogijun2018 requested changes

2024-05-20 08:02 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.trailing.equalTo(contentView.snp.trailing).offset(-35)
レイアウトをめちゃくちゃ大まかに図示するとこんな感じになると思うんだけど、
<img src=https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/10e9a763-6568-4eb7-af9d-c381570403dc  width=50%>

左端と右端のpaddingは全部20と35で同じだから、定数でまとめてしまえばここはもっと綺麗に書けるね。
```
enum Const {
  static let leftPadding = 20
  static let rightPadding = 35
}

        [nameLabel, descriptionLabel, userAccessoryView, starButton].forEach { view in
            view.snp.makeConstraints { constraint in
                constraint.leading.equalTo(contentView.snp.leading).offset(leftPadding)
            }
        }

        [nameLabel, descriptionLabel, userAccessoryView, languageNameLabel].forEach { view in
            view.snp.makeConstraints { constraint in
                constraint.trailing.lessThanOrEqualTo(contentView.snp.trailing).offset(-rightPadding)
            }
        }
```

みたいな感じ。こうすると 各Viewの制約をつける今のやり方とは変わってしまうけど、個人的にはこっちの方がわかりやすいと思うかなー
要素同士の間隔とかも定義してあげれば、もっと簡潔にかけるはず

DetailViewControllerの方も制約でめちゃくちゃ行数あるから、できたら先にここらへん整理してくれると助かるな

2024-05-20 08:23 UTC, Ogijun2018 requested changes

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +        // computed properties 62300 -> 6.2万
このコメントだと 62300 がなんか意味のある数字のように見えてしまうので、
`ex. 62300 -> 6.2万` とか、 `例: 62300 -> 6.2万` とか付けておいた方がいいね

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +        var formattedStringWithKanji: String {
この変数名だと `100` の場合も漢字にするの？ってなると思うから、 `stringFormattedStargazersCount` とかでいいんじゃないかな？

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +            guard let stargazersCount else { return "0" }
そもそもなんだけど、 stargazersCount とか languageとかって Optionalにしておく必要ってあるのかな？
APIの仕様を見てみると、 `type: null` ってなってるやつ以外は必ずレスポンスに含まれるんじゃないかな。
そうなのであれば `Repositories` のパラメータはOptionalである必要がなくなって、こういうguardも必要なくなるはず。
https://docs.github.com/ja/rest/search/search?apiVersion=2022-11-28#search-repositories

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +    }
この説明わかりやすくていいね 👍

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +    }
このfuncもう要らないはず。

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//        imageView.image = UIImage(systemName: "person.circle")?.withTintColor(.systemMint, renderingMode: .alwaysOriginal)
ここコメントアウトしてあるけど、もしconfigure() がうまくいかなかったときを考えるとここもあった方がいいかも。

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Enums/Constants.swift
> +    static let openIssuesExplainString: String = " issues"
これはDetailVCの方のコードかな。。？

2024-05-20 08:23 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +}
printログしかやっていなければここは消しちゃって欲しいです！

2024-05-20 09:52 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.trailing.equalTo(contentView.snp.trailing).offset(-35)
@Ogijun2018 
なるほど！forEach文でコードの量めちゃ減らせますね！ありがとうございます！
[cb205e8]にてコード修正しました！ご確認、お願いします！
また、DetailViewControllerの方も当該のbranchで作業しておきます！

2024-05-20 09:57 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +    }
@Ogijun2018 
ありがとうございます！今後も活かしてみます！

2024-05-20 10:02 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +    }
@Ogijun2018 
[1dc8e75]にて以下のコメントでレビューしていただいた箇所のコードを修正しました。
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1606412350
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1606409969

お手すきの際に、ご確認お願いします！

2024-05-20 10:45 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +            guard let stargazersCount else { return "0" }
@Ogijun2018 
[3f34d8f]と[e1389b4]にて、コードを修正しました。
送ってくださったAPIドキュメントに記載されている応答スキーマを参考にし、以下のように修正しました。
- `description`, `language`は `type: null`であるため、Optionalのままにしました。
- それら以外は、typeが決まっているため、Optionalを消しても正常な動作が確認できた。

2024-05-20 10:50 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//        imageView.image = UIImage(systemName: "person.circle")?.withTintColor(.systemMint, renderingMode: .alwaysOriginal)
@Ogijun2018 
そうですね、、defaultImageの設定をインスタンス生成時に設定しておきたかったのですが、configure()内でsd_setImageでerrorになる場合のdefualtImageを考えて、defaultImageの定義をconfigure()内にするようにしました。
[f2c398e]にてコード修正しましたので、ご確認お願いします！

2024-05-20 10:53 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Enums/Constants.swift
> +    static let openIssuesExplainString: String = " issues"
@Ogijun2018 
そうですね、、`DetailViewController`に関連するものをこのブランチでさっきに定義してしまいました。
今後、他のブランチで作業するものはコード書かないよう、心がけます！

2024-05-20 10:56 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +}
@Ogijun2018 
[1605541]にて、コード修正しました！他のブランチで作業が必要なコードは今後記載しないよう、心がけていきます！

2024-05-22 06:31 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Resources/Info.plist
> +	</dict>
@KyusokLee 
これの対応がまだされていなさそう

2024-05-22 06:32 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.flowLayout)
@KyusokLee 
これもまだ対応されていなさそう

2024-05-22 06:35 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.trailing.equalTo(contentView.snp.trailing).offset(-35)
leftPaddingとかrightPaddingは `HomeViewController` でしか使われない定数だから、わざわざ外に出す必要はないかな。
普通に `HomeViewController` 内でConst宣言してあげればいいと思う。
イメージはこんな感じ
https://github.com/st-tech/zozotown-ios/blob/76e1ba36e385203aa818a4d6fbfb62a28fbf6444/zozo/ViewControllers/CoordinateDetail/CoordinateDetailImageViewer/CoordinateDetailImageViewerViewController.swift#L69-L72

2024-05-22 06:36 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +            guard let stargazersCount else { return "0" }
良さそう！

2024-05-22 06:39 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//        imageView.image = UIImage(systemName: "person.circle")?.withTintColor(.systemMint, renderingMode: .alwaysOriginal)
あ、言いたかったのは宣言時に `imageView.image = UIImage(systemName: "person.circle")?.withTintColor(.systemMint, renderingMode: .alwaysOriginal)
` が設定されていれば、万が一configure()でうまくいかなかったときでも宣言時に設定画像が設定されているから、意図しない表示にならなくなるから残しておいた方がいいんじゃない？ってことだね

なので、対応としてはコメントアウトを戻してあげるだけでよかった

2024-05-22 06:40 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +}
そもそもextension自体も使っていないなら消しちゃってもよさそうだけど、今後使う予定がありそうってことなら残しておいてよさそう

2024-05-22 06:43 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +        var formattedStringWithKanji: String {
@KyusokLee 個人的にフォーカスしたいのは、 `withKanji` の方だね。 withKanjiが入ってると漢字にしない場合もあることが表現できてないから、 `withKanji` は不要そう

2024-05-22 06:59 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Resources/Info.plist
> +	</dict>
@Ogijun2018 
[7747970]にて、コード修正しました！ご確認、お願いします！

2024-05-22 07:01 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        let collectionView = UICollectionView(frame: .zero, collectionViewLayout: self.flowLayout)
@Ogijun2018 
[4aabba8]にて、コード修正しました！ご確認、お願いします！

2024-05-22 07:15 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +            constraint.trailing.equalTo(contentView.snp.trailing).offset(-35)
[c4cba9d]にて、コード修正しました！
コメントいただいた内容と似たようなコードを`feature/DetailViewController`でも書いてしまったため、こちらも合わせて修正後、該当ブランチにコミットしておきます。
また、`RepositoryCollectionViewCell`内の`setAddSubViews`メソッド内で処理していた、Cellの各UIの`contentView.addSubView`作業を `forEach`文を用いた処理に変更しました。
ご確認、お願いします！

2024-05-22 07:18 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +        var formattedStringWithKanji: String {
@Ogijun2018 
確かに、おっしゃる通り漢字にしない場合もあることが表現できてないので、パッと見でわかりやすい変数名ではありませんでした。。
[f599490]にて、コード修正しましたので、ご確認お願いします！

2024-05-22 07:30 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//        imageView.image = UIImage(systemName: "person.circle")?.withTintColor(.systemMint, renderingMode: .alwaysOriginal)
あ、なるほどですね、、！理解を間違えちゃいました。。！
[f73fc2b]にて、コード修正しましたので、お手すきの際に、ご確認お願いいたします！

2024-05-23 10:07 UTC, Ogijun2018 requested changes

2024-05-23 10:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        navigationController?.navigationBar.scrollEdgeAppearance = appearance
[IMO (In My Opinionなので修正する必要は特にないですが)]
今回の要件的にはstandardAppearanceだけが設定されていれば良いので、現時点だけで言うと特に必要ないかなとも思う。（けど、ここから拡張して横画面対応とかヘッダーを表示するとかあるかもしれないから、ある分には良さそう）

2024-05-23 10:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/RepositoriesResponse.swift
>  */
ぎゅが作ってくれたコンフルのAPI仕様だったり、GitHubのAPIのページをここにコメントで残しておくと親切だね！

2024-05-23 10:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +            return stargazersCount >= Constants.numberFormatThreshold ? String(format: "%.1f万", Double(stargazersCount) / Double(Constants.numberFormatThreshold)) : String(stargazersCount)
1文なのでreturnいらないっす。
```suggestion
            stargazersCount >= Constants.numberFormatThreshold ? String(format: "%.1f万", Double(stargazersCount) / Double(Constants.numberFormatThreshold)) : String(stargazersCount)
```

2024-05-23 10:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +/// UICollectionViewCellにaccessoryTypeを表すために、UICollectionViewから UICollectionViewListCellに変更
doc-commentの使い方なんだけど、たとえば `RepositoryCollectionViewCell` を使おうかな〜って思って候補を見た時にこのコメントを見たところで「このセルがなんのセルなのか」がわからないから↓

<img width="1019" alt="スクリーンショット 2024-05-23 19 01 35" src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/0938cb28-2a28-46ff-929b-2d76713f80a1">

ここではたとえば
`リポジトリの情報を表示するセル` みたいに書くのが普通かな。

`UICollectionViewCellにaccessoryTypeを表すために、UICollectionViewから UICollectionViewListCellに変更` 「変更した」っていう情報はgithub上に残ってるわけだから、コメントとして残さなくても良さそう

2024-05-23 10:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
ここまとまってすごくよい。よりまとめるなら、こうすることもできる
```suggestion
        [userAccessoryView, starButton, starCountsLabel, languageColorView, languageNameLabel].forEach {
            contentView.addSubview($0)
        }
```

2024-05-23 10:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
[IMO] ここも短縮形を使うならこんな感じにもできる。
```suggestion
        [nameLabel, descriptionLabel, userAccessoryView, starButton].forEach {
            $0.snp.makeConstraints { $0.leading.equalTo(contentView.snp.leading).offset(Constants.leftPadding) }
        }
```

2024-05-23 10:26 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        navigationController?.navigationBar.scrollEdgeAppearance = appearance
確かに、、おっしゃる通り、横向きの画面は必要ないと考えるため、`compactAppearance`と`compactScrollAppearance`は削除しておきました。`scrollEdgeAppearance`も、scroll時の挙動として今回はいらないと思ったため、削除しておきました。
[fe2554a] [17e6a36]　にてコード修正しましたので、ご確認お願いします！

2024-05-23 10:31 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Entities/RepositoriesResponse.swift
>  */
[ed5c0bf]にてコード修正しました！ご確認、お願いします！
今回は、GitHubのAPIのページのみ、コメントに残しておきました！コンフルのURLは、プライベート（会社のページ）であるため残さないようにしました！

2024-05-23 10:33 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Presentations/Repositories.swift
> +            return stargazersCount >= Constants.numberFormatThreshold ? String(format: "%.1f万", Double(stargazersCount) / Double(Constants.numberFormatThreshold)) : String(stargazersCount)
[10f1a9a]にて、コード修正しましたので、ご確認お願いします！

2024-05-23 10:37 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +/// UICollectionViewCellにaccessoryTypeを表すために、UICollectionViewから UICollectionViewListCellに変更
確かに！おっしゃる通り、何のcellなのかパッと見でわかりずらかったですね、、
今後、説明のコメントはできる限り、わかりやすくて短くするようにしておきます！ありがとうございます！
[df9adb2]にてコード修正しましたので、ご確認お願いします！

2024-05-23 10:46 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
そうですよね！略式の書き方にするか迷ったんですけど、forEachのパラメータが何を表すか端的に書いた方がいいかなと思って、略式の表現ではなく `view`や`constraint`のように書いてました！ただし、パラメータの名前も長くなる可能性もあるので、確かに略式でいいかも！って思いました！

[6ec7848]にて　
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1611394374
の内容も踏まえて、コード修正しました！ご確認、お願いいたします！

2024-05-24 01:51 UTC, Ogijun2018 approved these changes
![LGTM](https://image.lgtmoon.dev/248351)

2024-05-24 06:02 UTC, merged