リポジトリの詳細情報を表示するDetailViewControllerの実装
KyusokLee/CodeAssignment_MVVM_Combine pull request #5
Opened 2024-05-20 03:50 UTC by KyusokLee

## 何故やるのか
- `NavigationController`を基盤に`CollectionView`のCellをタップしたら、他のViewControllerに画面遷移される流れの実装・理解のため
- 詳細画面でより多くの情報を表示するときのコードベースのlayout設定を用いた実現方法を理解するため

## 変更点
`UICollectionViewListCell`をタップしたら`DetailViewController`に画面が遷移される。また、`Repositories`に`watchersCount`, `forksCount`, `openIssuesCount`のデコードして取得する情報を足し、その情報をタップしたcellに表示した情報とともに`DetailViewController`に表示する。

## 期待される結果
`UICollectionViewListCell`をタップすると`DetailViewController`に画面遷移され、タップした`Cell`に表示されていたリポジトリの内容に`watchersCount`, `forksCount`, `openIssuesCount`を加えた情報も表示される。

## 動作確認方法
- 録画動画

## スクリーンショット・録画（あれば）
<video src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/89962765/9f5fbc37-c31b-4eb2-acf0-537b039e7b3f">

2024-05-24 01:55 UTC, Ogijun2018 requested changes

2024-05-24 01:55 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Enums/Constants.swift
> +import UIKit
これ必要？

2024-05-24 06:03 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Enums/Constants.swift
> +import UIKit
[cf73e08]にてコード修正しました！ご確認、お願いいたします！

2024-05-27 03:16 UTC, Ogijun2018 requested changes
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4 でmainに含めたはずの変更もこのPRに入ってしまっているので、解決お願いします 🙏

2024-05-27 11:25 UTC, Ogijun2018 requested changes

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    static let openIssuesExplainString: String = " issues"
この定数の中で空白を入れてスタイルの制御はしない方が良さそう。
ここのスペースはconfigure()の中で
```
"\(formatNumberToStringWithSeparator(model.stargazersCount)) \(Const.starsExplainString)"
```
ってやる方がよさそう。

あとはそもそもここが定数として必要かどうかかな… `watchersに関するString型の説明文` って書いてあるけど、説明文にはなってない気がする。。

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    static let colorViewHeightSize: CGFloat = 20
```suggestion
    static let colorViewHeight: CGFloat = 20
```
Sizeって入れなくてもHeightが「高さ」なので伝わるね

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    /// ScrollViewで、backgroundCardViewをScroll可能にする
doc-commentの意味を思い出して！

https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/4#discussion_r1611392227

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
ここ普通にinitでいいと思う

```
init(repository: Repositories.Repository) {
        super.init(nibName: nil, bundle: nil)
        self.configure(with: repository)
    }
```

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupConstraints() {
制約すごいことになっちゃってると思うんだけど、等間隔でViewを置いていくんだったらUIStackViewを使った方が綺麗で簡単に書けるんじゃないかな？

https://developer.apple.com/documentation/uikit/uistackview

一つの大きいStackViewを作ってsubViewsにすべて入れれば、左右のpaddingとかも1文で設定できる
それぞれの要素の間隔も一応設定できるから、試してみて
https://developer.apple.com/documentation/uikit/uistackview/2865827-customspacing

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +//        navigationController?.navigationBar.tintColor = .black
不要なコード

2024-05-27 11:25 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/HomeViewController.swift
> +        navigationController?.navigationBar.topItem?.setHidesBackButton(true, animated: false)
これってどういう意図で入れてる？必要なのかな

2024-05-27 11:31 UTC, Ogijun2018 requested changes

2024-05-27 11:31 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
>          return button
```suggestion
        return UIButton(configuration: config)
```
変数作る意味なさそう

2024-05-28 06:35 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    static let openIssuesExplainString: String = " issues"
スペース入りのスタイル制御はよくないとのこと、承知しました。

> あとはそもそもここが定数として必要かどうかかな… watchersに関するString型の説明文 って書いてあるけど、説明文にはなってない気がする。。

確かに、おっしゃる通りに説明文にもなってないし、直接"watchers"など記入した方が良さそうですね！最初の意図としては、コラボレートする人がいると想定し、今後のコード修正時にここの"stars"や"forks"などの文字が何を表すかを明確に伝えたるようにしたく、定数として設計しました。
[b6ed2d8]にてコード修正しましたので、ご確認お願いいたいます！

2024-05-28 06:44 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    static let colorViewHeightSize: CGFloat = 20
ここも[b6ed2d8]にて修正しました！ご確認お願いします！

2024-05-28 06:49 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    /// ScrollViewで、backgroundCardViewをScroll可能にする
> doc-commentの意味を思い出して！

修正漏れでした！今後気をつけます📝
[f48cdeb]にて、修正しました！

2024-05-28 07:09 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
`override init`ではなく、`init`にパラメータを入れてカスタマイズできるのを初めて知りました！勉強になります！
[60690ce]にてコード修正しました！お手すきの際に、ご確認お願いします！

2024-05-28 08:38 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
>          return button
[045e9a4]にて下記のコメントの内容も含めて、修正しました。ご確認お願いします！

https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5#discussion_r1615907368
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5#discussion_r1615909959

2024-05-28 10:02 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupConstraints() {
[5937e7a]にて、コード修正しました！ご確認、お願いします！

2024-05-29 02:50 UTC, Ogijun2018 requested changes

2024-05-29 02:50 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
contentViewってそもそもいるのかな？ contentViewがなくても、 `backgroundCardView` にこんな感じで制約つけてあげれば表示は問題ないと思う。ちょっと試してみてほしい！

```
--- a/CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
+++ b/CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
@@ -27,13 +27,7 @@ final class DetailViewController: UIViewController {
         scrollView.showsVerticalScrollIndicator = true
         return scrollView
     }()
-
-    /// ScrollViewのContentView
-    private lazy var contentView: UIView = {
-        let view = UIView()
-        return view
-    }()
-
+
     /// リポジトリのデータを入れるbackgroundView
     private lazy var backgroundCardView: UIView = {
         let view = UIView()
@@ -264,9 +258,8 @@ extension DetailViewController {
         [userImageView, userNameLabel, mainStackView].forEach {
             backgroundCardView.addSubview($0)
         }
-
-        contentView.addSubview(backgroundCardView)
-        scrollView.addSubview(contentView)
+
+        scrollView.addSubview(backgroundCardView)
         view.addSubview(scrollView)
     }

@@ -275,16 +268,11 @@ extension DetailViewController {
             constraint.edges.equalTo(view.safeAreaLayoutGuide)
         }

-        contentView.snp.makeConstraints { constraint in
-            constraint.edges.equalTo(scrollView.contentLayoutGuide)
-            constraint.width.equalTo(scrollView.frameLayoutGuide)
-        }
-
         backgroundCardView.snp.makeConstraints { constraint in
-            constraint.top.equalTo(contentView.snp.top).offset(30)
-            constraint.leading.equalTo(contentView.snp.leading).offset(Const.leftPadding)
-            constraint.trailing.equalTo(contentView.snp.trailing).offset(-Const.rightPadding)
-            constraint.bottom.equalTo(contentView.snp.bottom).offset(-30)
+            constraint.top.equalTo(scrollView.snp.top).offset(30)
+            constraint.width.equalTo(scrollView.snp.width).offset(-(Const.leftPadding + Const.ri
ghtPadding))
+            constraint.centerX.equalTo(scrollView.snp.centerX)
+            constraint.bottom.equalTo(scrollView.snp.bottom).offset(-30)
         }

         userImageView.snp.makeConstraints { constraint in
```

2024-05-29 02:50 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
Gatherで話した通り、この辺りのStackViewはなくても実装できるので、試してみてください！イメージとしては

- userImageView(imageViewをそのまま入れるとcornerRadiusが効かなくなるはずなので、外に一つUIViewを噛ませる必要がある)
- userNameLabel
- repositoryNameLabel
- descriptionLabel
- starLanguageStackView
- countStackView

この6つのViewがmainStackViewのarrangedSubViewsに入るイメージ。 これらのView間の余白はsetCustomSpacingで変えられるので、今実装している余白は再現可能なはず。

<img src=https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/278e0dae-3790-4152-8e3a-a7750914cd95  width=50%>

2024-05-29 02:59 UTC, Ogijun2018 requested changes

2024-05-29 02:59 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
☆をつけようと思ったら、今の場合だと☆の画像部分をタップしないとボタンを押したことにならないと思うんだけど、ボタン自体が結構小さいのでユーザーさんは押しづらいと思うかもしれないね。
個人的にはstarCountLabelまでをボタンの範囲にしてあげたほうがユーザビリティ的な観点でも良さそうだと思う。

ちなみに、AppleのHuman Interface Guidelinesには「ボタンは44pt × 44pt以上にするように」っていうガイドラインもある。
https://developer.apple.com/design/human-interface-guidelines/buttons#Best-practices
今の☆のボタンは20×20だと思うから、これは満たしてなさそうだね。

UIButtonにラベルも入れられるので、これを使ってみるのはどうかな？
https://qiita.com/_asa08_/items/7b2e26181ce1ee18df75

2024-05-29 03:07 UTC, Ogijun2018 requested changes

2024-05-29 03:07 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
このラベルたちはスタイルが完全に同じだから、DRY原則にしたがってLabelを作ってあげるprivate funcを作った方が良さそう。

```
    private lazy var watchersCountLabel: UILabel = makeCountLabel()
    private lazy var forksCountLabel: UILabel = makeCountLabel()
    private lazy var openIssuesCountLabel: UILabel = makeCountLabel()

    private func makeCountLabel() -> UILabel {
        let label = UILabel()
        label.font = .systemFont(ofSize: 18, weight: .regular)
        label.textColor = .black.withAlphaComponent(0.7)
        return label
    }
```

2024-05-29 03:10 UTC, Ogijun2018 requested changes

2024-05-29 03:10 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
>      }()
こっちも https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/files#r1618117541 と同じ指摘。

2024-05-29 03:10 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupConstraints() {
別の場所で続きの指摘したのでここは一旦閉じる

2024-05-29 03:18 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
[8a61fce]にて、コード修正しました！ご確認お願いします！

2024-05-29 03:34 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
`RepositoryCollectionViewCell`にも似たような重複コードがあったので、そちらも合わせて修正しました。
[3ce6c91]の方、ご確認お願いいたします！

2024-05-29 03:48 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
contentView消えてないね

2024-05-29 10:37 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
[a9a2b6b]にて、コード修正しました！ご確認お願いします！

2024-05-29 10:37 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }()
[a9a2b6b]にて、コード修正しました！ご確認お願いします！

2024-05-29 11:13 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
>      }()
[99dd9c7]にてコード修正しました！
ここでは、`starButton`に`starCountsLabel`を入れず、Buttonの方を`UIImage.SymbolConfiguration(pointSize: _ , weight: _ )`を用いてImage自体を大きくしました。ご確認、お願いします！

2024-06-04 11:30 UTC, Ogijun2018 requested changes

2024-06-04 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
userNameLabelはもうStackViewの中に入ってるから、offsetとかを指定する必要はないね。leading/trailingもmainStackViewに対してしているはずだから、ここはこんな感じになるはず。
```suggestion
        userImageView.snp.makeConstraints { constraint in
            constraint.top.equalTo(userImageContentView.snp.top)
            constraint.height.equalTo(250)
            constraint.width.equalTo(250)
            constraint.centerX.equalTo(userImageContentView.snp.centerX)
            constraint.bottom.equalTo(userImageContentView.snp.bottom)
        }
```

2024-06-04 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
guardで書いてあげたほうが入れ子にならなくて読みやすいかな。

```suggestion
        guard let url = URL(string: model.owner.profileImageString) else { 
            userImageView.image = defaultImage
            return
        }
        userImageView.sd_setImage(with: url, placeholderImage: defaultImage) { [weak self] (image, error, _, _) in
            guard let self else { return }
            guard let error else {
                self.userImageView.image = image
                return
            }
            self.userImageView.image = defaultImage
        }
```

2024-06-04 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
ここは if varでやってもいいけど、↓とやってること変わらないからこっちのほうがシンプルでいいかも。
わざわざconfigurationを入れ直してるのも冗長かなと思うので
```suggestion
        starButton.configuration?.attributedTitle = AttributedString(
            "\(formatNumberToStringWithSeparator(model.stargazersCount)) stars",
            attributes: AttributeContainer([
                .font: UIFont.systemFont(ofSize: 20, weight: .regular),
                .foregroundColor: UIColor.black.withAlphaComponent(0.8)
            ])
        )
```

2024-06-04 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        label.setContentHuggingPriority(.init(999), for: .horizontal)
マジックナンバーはつくらないほうがいいですね
```suggestion
        label.setContentHuggingPriority(.required, for: .horizontal)
```

2024-06-04 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        return button
このあたりの空白、スペースが入っちゃってると思うんだけど、zozotown-iosでは空行はスペースを入れない設定にしてます！XcodeのSettingsのところでincluding whitespace-only linesってところにチェック入れればそうなるはず！

<img width="942" alt="スクリーンショット 2024-06-04 20 23 36" src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/0e71d9e1-1025-4486-afca-b044c528559e">

```suggestion
    private lazy var starButton: UIButton = {
        var config = UIButton.Configuration.filled()
        let image = UIImage(systemName: "star")?.withTintColor(.systemGray3, renderingMode: .alwaysOriginal)
        if let image {
            config.image = image.withConfiguration(UIImage.SymbolConfiguration(pointSize: 25, weight: .regular))
        }
        config.baseBackgroundColor = .white
        config.imagePlacement = .leading
        // imageとtext間のSpace
        config.imagePadding = 8
        config.contentInsets = .init(top: 10, leading: 8, bottom: 10, trailing: 8)
        config.cornerStyle = .large

        // borderLayerの設定
        var backgroundConfig = UIBackgroundConfiguration.clear()
        backgroundConfig.strokeColor = .systemGray2
        backgroundConfig.strokeWidth = 2
        config.background = backgroundConfig

        let button = UIButton(configuration: config)
        // content hugging priorityを設定し、buttonのconstraintsが意図通りに設定されないことを防ぐ
        button.setContentHuggingPriority(.required, for: .horizontal)
        button.setContentCompressionResistancePriority(.required, for: .horizontal)
        button.titleLabel?.setContentHuggingPriority(.required, for: .horizontal)
        button.titleLabel?.setContentCompressionResistancePriority(.required, for: .horizontal)

        return button
```

2024-06-04 11:30 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +            constraint.width.equalTo(Const.colorViewHeight)
`Height` って入れてるのに width に設定してるのが違和感あるね。Constの名前を変更したほうが良さそう。
例えば `colorViewSize` とか。

2024-06-04 11:52 UTC, Ogijun2018 requested changes

2024-06-04 11:52 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
ここってそもそもconfig.imageが受け取るのは `Image?` 型だから、if letをやる必要ないんじゃないかな？
```suggestion
        config.image = UIImage(systemName: "star")?.withTintColor(.systemGray3, renderingMode: .alwaysOriginal).withConfiguration(UIImage.SymbolConfiguration(pointSize: 25, weight: .regular))
```

2024-06-04 11:52 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
ここも上の指摘と同様
```suggestion
        config.image = .init(systemName: "star")?.withTintColor(.systemGray3, renderingMode: .alwaysOriginal).withConfiguration(UIImage.SymbolConfiguration(pointSize: 22, weight: .regular))
```

2024-06-04 11:52 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        return button
huggingPriorityとかはsetConstraintsのところでやったほうがいいかも。これも制約なので、場所が分かれてるとわかりずらくなっちゃいそう。

```suggestion        
        return UIButton(configuration: config)
```

2024-06-04 11:52 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//            constraint.centerY.equalTo(starCountsLabel.snp.centerY)
いらないコメントアウトは消しましょう

2024-06-04 11:52 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//            constraint.bottom.lessThanOrEqualTo(contentView.snp.bottom).offset(-8)
いらないコメントアウトは消しましょう

2024-06-05 03:00 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
[50e3a16]にて、コード修正しました！ご確認お願いします！

2024-06-05 03:11 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
[c984c15]にてコード修正しました！ご確認お願いします！

2024-06-05 03:16 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
[d86806d]にてコード修正しました！ご確認お願いします！

2024-06-05 03:20 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        label.setContentHuggingPriority(.init(999), for: .horizontal)
[7c2bd26]にてコード修正しました！ご確認お願いします！

2024-06-05 04:22 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        return button
[e2ef9f8]にてコード修正しました！ご確認お願いします！

2024-06-05 04:29 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +            constraint.width.equalTo(Const.colorViewHeight)
[719bf78](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/commits/719bf78d3eff6dd6bd759f3f099a8657a95866e7)にて、コード修正しました！ご確認お願いします！

2024-06-05 04:32 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
[a798e26](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/commits/a798e26e9c0db810c0885d866e2aa90f9a8ad337)にてコード修正しました！ご確認お願いします！

2024-06-05 04:34 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +        }
[b1bd202](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/commits/b1bd202931c850a53519ae7d495c85aaf8baed37)にてコード修正しました！ご確認お願いします！

2024-06-05 06:07 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        return button
[a459314](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/commits/a459314d2896307f45a692434d14e7b886a8fef6)にてコード修正しました！ご確認お願いします！

2024-06-05 06:08 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//            constraint.centerY.equalTo(starCountsLabel.snp.centerY)
[fd8b510](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/commits/fd8b510462662bc234d2286d366bdaf86b4c0fea)にてコード修正しました！ご確認お願いします！

2024-06-05 06:08 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Views/Cells/HomeViewController/RepositoryCollectionViewCell.swift
> +//            constraint.bottom.lessThanOrEqualTo(contentView.snp.bottom).offset(-8)
[fd8b510](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/5/commits/fd8b510462662bc234d2286d366bdaf86b4c0fea)にてコード修正しました！ご確認お願いします！

2024-06-05 08:59 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        return button
他の空行も余分なスペース入っちゃってるんだけど、設定さえしてくれてればOKなのでResolveします。

2024-06-05 09:04 UTC, Ogijun2018 requested changes

2024-06-05 09:04 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    /// DetailViewControllerで表すLanguageColorViewのHeight
```suggestion
    /// DetailViewControllerで表すLanguageColorViewのサイズ
```

2024-06-05 09:09 UTC, Ogijun2018 commented
![LGTM](https://image.lgtmoon.dev/249934)

2024-06-05 09:09 UTC, merged