リポジトリにスターの付け・解除が可能な機能実装
KyusokLee/CodeAssignment_MVVM_Combine pull request #6
Opened 2024-05-24 09:53 UTC by KyusokLee

## 何故やるのか
- Access Tokenを用いたAPI叩きを理解するため

## 変更点
`starButton`をタップしたら、`isSelected`が`true`の場合はスター付けを、`false`の場合はスター解除をするようにした。

## 期待される結果
`starButton.isSelected`が`true`の場合は`DetailViewController`にバインディングした`DetailViewModel`の`starRepository`メソッドを通して、スターボタンが黄色に変更される。一方で、`false`の場合はVMの`unstarRepository`メソッドを通してスターボタンの色が消える。

## 動作確認方法
- 録画動画

## スクリーンショット・録画（あれば）
<video src="https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/89962765/6dc66c40-32d4-4e80-aee8-a504d353fa95">

2024-06-04 12:28 UTC, Ogijun2018 requested changes

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine.xcodeproj/xcuserdata/gyusoku.i.xcuserdatad/xcschemes/xcschememanagement.plist
> +	</dict>
これって必要な差分？

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine.xcodeproj/xcshareddata/xcschemes/CodeAssignment_MVVM_Combine.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
このファイルも必要な差分なのかな？

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
星ボタンを押しても隣のstarCountが増えたり減ったりしないのは不自然かもね。
もう一度リポジトリの情報を取得してくるのはめんどくさいと思うから、単純にcount部分を +1 / -1してあげるだけとかやってみるとユーザーさんからするとフィードバックが来てわかりやすいね。

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
>              return request
この2つのcaseで違うのって `request.httpMethod = ` の部分だけでそれ以外は共通化できると思うから、caseの引数に `starStatus: Bool` を加えたcaseを作って、
`.starRepository(let owner, let repo, starStatus: Bool):`

このcaseの中で `starStatus` がtrueかfalseかによってhttpMethodを変えるってやればきれいにできそうだね。

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +                    completion(.success(nil))
複数のcaseの中で同じ処理を行う場合、caseはまとめて書けるし、中の引数を使わない場合は省略できる。
```
                case .starRepository, .unstarRepository:
                    // リポジトリにスター付け・解除はdecode作業は不要なため、completionはsuccessのみ返す
                    // Modelの返り値はいらないので、nil
                    completion(.success(nil))
                }
```

けど、caseは他の指摘で1つにまとまりそうだから知っておいてくれればOK。

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +        let requestProtocol = GitHubSearchRepositoriesRequest(searchQueryWord: "")
そもそもここは `GitHubSearchRepositoriesRequest(searchQueryWord: "")` だから、検索のためのリクエストを使っちゃってるね。 スターをつけるための `GitHubStarRequest` 的なのを別途作ったほうがいいね。

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        starButton.isSelected.toggle()
starButtonの今の状態（選択状態か非選択状態か）はViewModel側で管理して、viewModel側のisSelectedが変わったことを検知してstarButton.isSelectedを変更したほうがよさそう。
今だとViewModelがある意味があんまりなくなっちゃってるね

2024-06-04 12:28 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        starButton.isSelected.toggle()
starRepositorySubjectが実質今のisSelectedと対応してると思うから、ここは本来いらないコード何じゃないかな？

2024-06-05 07:05 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine.xcodeproj/xcuserdata/gyusoku.i.xcuserdatad/xcschemes/xcschememanagement.plist
> +	</dict>
[252716f](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/252716f05694cc23981588855a2f5a5f15e7fec8)にて修正しました。ご確認お願いします！

2024-06-05 07:05 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine.xcodeproj/xcshareddata/xcschemes/CodeAssignment_MVVM_Combine.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
[252716f](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/252716f05694cc23981588855a2f5a5f15e7fec8)にて修正しました。ご確認お願いします！

2024-06-05 09:49 UTC, Ogijun2018 commented
コンフリクト起きてるので解消もお願いします！

2024-06-05 11:08 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
[f8d36ea](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/f8d36ea2f6930ce168c8ca718821d4789d3b36b3)にて、修正しました！ご確認お願いします！

2024-06-06 06:49 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
>              return request
[2aa2d0b](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/2aa2d0b222a5820a4b59cf61127c9faf812695f5)にてコード修正しました！ご確認お願いします！

2024-06-06 07:01 UTC, Ogijun2018 requested changes

2024-06-06 07:01 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +            }
三項演算子使いましょう！
`request.httpMethod = starStatus ? "PUT" : "DELETE"`

2024-06-06 10:12 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +        let requestProtocol = GitHubSearchRepositoriesRequest(searchQueryWord: "")
[40f5ce6](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/40f5ce625c1109ee71a787ecf45a2dc1c86437aa)にてコード修正しました！お願いします！

2024-06-06 10:14 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +            }
[e7c85fd](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/e7c85fded8a082df639bdf9cfae739af344f4f76)にて修正しました！ご確認お願いします！

2024-06-06 10:32 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        starButton.isSelected.toggle()
[5c4d791](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/5c4d791ac886823c3475b6c5b463cd7d0baf9383)にてコード修正しました！ご確認お願いします！

2024-06-07 11:41 UTC, Ogijun2018 requested changes

2024-06-07 11:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    static let decrement: Int = -1
さすがにインクリメント・デクリメントはConstに定義しなくてもわかるから作らなくていいよ笑

2024-06-07 11:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +            }
MVVMでやるなら、ボタンの状態（スターをつけた状態かどうか）はViewModel側で持っておいて、そのボタンの状態が変わったことを検知してViewControllerが色を変える、っていうデータフローにするのがいいかな。

2024-06-07 11:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
こういった内部の状態変化（ビジネスロジック）はViewModel側でやるべきことだね。あと、そもそもupdateStarGazersCountでもらってくるtitle（多分stargazersCountのことだと思うけど）は元がIntなはずだから、それを使ってあげた方が良さそう。

2024-06-07 11:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
ViewModel側に持ってきてあげたらこのfunc自体なくせるかな。

2024-06-07 11:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
ここはprivateじゃないけどExtensionにあっても問題ない？（どういうふうにExtensionに切り出しているのかわからなかった）

2024-06-07 11:41 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        viewModel.starRepository(owner: userNameLabel.text!, repo: repositoryNameLabel.text!, starStatus: !starButton.isSelected)
ViewModel側でrepositoryの情報を持っておけば、ここで値を渡す必要はなくなるはず。
あと、func名も `starRepository` だと何をした時のアクションなのかわからないから、普通に `didTapStarButton` でいいと思うよ

2024-06-07 12:06 UTC, Ogijun2018 commented
多分修正する方向性が↑のコメントだとわからないと思うから、サンプルで自分が実装したPR作っておきました。
https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/9
一旦このPRは見ないで、もしつまづいたら参考にしてみてください。

2024-06-10 03:36 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    static let decrement: Int = -1
[26cd4d0](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/26cd4d0e0f5f6b96dcbcbeb1319f72fe58a4fca5)にてコード修正しました！ご確認お願いします！

2024-06-10 03:51 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
申し訳ないです、、！privateつけ忘れました、、
[7d0f5b0](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/7d0f5b0ac8ec85340c56e2c2db7ccedbdab5d06f)にてコード修正しました！ご確認お願いします！

2024-06-11 09:38 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
[77e2b9f](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/77e2b9fefdda4cb3f86ba29ff5765b6c7bfb19d6)にてコード修正しました！ご確認お願いします！

2024-06-11 09:38 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        viewModel.starRepository(owner: userNameLabel.text!, repo: repositoryNameLabel.text!, starStatus: !starButton.isSelected)
[77e2b9f](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/77e2b9fefdda4cb3f86ba29ff5765b6c7bfb19d6)にてコード修正しました！ご確認お願いします！

2024-06-12 02:47 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +            }
[77e2b9f](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/77e2b9fefdda4cb3f86ba29ff5765b6c7bfb19d6)にてコード修正しました！ご確認お願いします！

2024-06-14 06:19 UTC, Ogijun2018 requested changes

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
ここもういらないよね。

```suggestion
```

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine.xcodeproj/xcshareddata/xcschemes/CodeAssignment_MVVM_Combine.xcscheme
> +<?xml version="1.0" encoding="UTF-8"?>
これ結局差分として含まれちゃってるね。

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine.xcodeproj/xcuserdata/gyusoku.i.xcuserdatad/xcschemes/xcschememanagement.plist
> +	</dict>
これもまだ差分が消えてないね。

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
これ結局 `setupStarButtonAttributedTitle()` を呼んでいるだけなら、 `updateStarGazersCount()` を呼ばないで直接中のfunc呼べばいいからいらなさそう。

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupStarButtonAttributedTitle(with title: String) {
`setup` だと初回設定用のfuncみたいに見えるかな。 `updateStarGazersCount()` で更新時にも呼ばれてるから、 `setup` というよりかは `set` とか `update` とかが適切だと思う。

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupStarButtonAttributedTitle(with title: String) {
`setup` だと初回設定用のfuncみたいに見えるかな。 `updateStarGazersCount()` で更新時にも呼ばれてるから、 `setup` というよりかは `set` とか `update` とかが適切だと思う。

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +    func buildUpRequest(type: GitHubAPIType) -> URLRequest? {
使っていないのでtype不要

```suggestion
    func buildUpRequest() -> URLRequest? {
```

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
>      func buildUpRequest(type: GitHubAPIType) -> URLRequest? {
使っていないのでtype不要

```suggestion
    func buildUpRequest() -> URLRequest? {
```

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +        let requestProtocol = GitHubStarRepositoryRequest(owner: repository.owner.userName, repository: repository.name, starStatus: !isStarred)
好みの問題だけど、引数が長くなる時は改行してあげたほうが見やすい

```suggestion
        let requestProtocol = GitHubStarRepositoryRequest(
            owner: repository.owner.userName,
            repository: repository.name,
            starStatus: !isStarred
        )
```

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +        let requestProtocol = GitHubStarRepositoryRequest(owner: repository.owner.userName, repository: repository.name, starStatus: !isStarred)
加えて、`GitHubStarRepositoryRequest` はプロトコルではないので変数名が不自然ですね。
普通に `let request` とかでいいと思う

2024-06-14 06:19 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +                    print(error.errorTitle)
本来であればエラーが起きた時はユーザーに伝わるようにアラートなどを表示するべきだね。
今回は対応してもしなくてもいいです。

2024-06-14 08:59 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +        }
修正漏れ、大変失礼しました。。！
[3c1e5f0](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/3c1e5f0a492cf65904b45d1c0e26fa322c058c8b)にてコード修正しました。ご確認お願いします！

2024-06-14 09:09 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    }
確かにそうですね.... 無意識で全部細かくしようという考えだったかもしれないです。。今後注意します！
[16fa84f](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/16fa84f2d62a7159b765404bf5103a89415dfbfe)にてコード修正しました。ご確認お願いします！

2024-06-17 03:56 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupStarButtonAttributedTitle(with title: String) {
[f8f5e2b](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/f8f5e2bf1d6a9d3f76300ceb41c49b9ef3815ce8)にてコード修正しました！ご確認お願いします！

2024-06-17 03:56 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
> +    private func setupStarButtonAttributedTitle(with title: String) {
[f8f5e2b](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/f8f5e2bf1d6a9d3f76300ceb41c49b9ef3815ce8)にてコード修正しました！ご確認お願いします！

2024-06-17 03:58 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
> +    func buildUpRequest(type: GitHubAPIType) -> URLRequest? {
[e60c575](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/e60c575b68745a476e7834316887c1592fa89e39)にてコード修正しました！ご確認お願いします！

2024-06-17 03:59 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/Models/Network/APIClient.swift
>      func buildUpRequest(type: GitHubAPIType) -> URLRequest? {
[e60c575](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/e60c575b68745a476e7834316887c1592fa89e39)にてコード修正しました！ご確認お願いします！

2024-06-17 04:02 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +        let requestProtocol = GitHubStarRepositoryRequest(owner: repository.owner.userName, repository: repository.name, starStatus: !isStarred)
[cd05ef6](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/cd05ef6cbd4c6332eb7e536caa2308f7d44946e7)にてコード修正しました！ご確認お願いします！

2024-06-17 07:36 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +                    print(error.errorTitle)
[590e263](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/590e2631acfa901589f68befe4547b9103300d84)にて`UIAlertController`を用いてエラーをユーザに表示するようにコードを修正しました。ご確認お願いします！

2024-06-17 09:26 UTC, Ogijun2018 requested changes

2024-06-17 09:26 UTC, Ogijun2018 commented on .gitignore
> +*.xcuserdata
```suggestion
CodeAssignment_MVVM_Combine.xcodeproj/xcuserdata
```

2024-06-17 09:34 UTC, KyusokLee commented on .gitignore
> +*.xcuserdata
[66c44a3](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/66c44a3b449c2c4fe72dac8c9e07dff24490a188)にてコード修正しました！ご確認お願いいたします！

2024-06-17 09:59 UTC, Ogijun2018 requested changes

2024-06-17 09:59 UTC, Ogijun2018 commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +    @Published private(set) var errorMessage: String? = nil
ここで扱うデータを `ErrorType?` 型にしてしまえば、ViewController側ではerrorTypeをそのまま `presentErrorAlert` するだけでよくなるよね。

```
--- a/CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
+++ b/CodeAssignment_MVVM_Combine/Sources/Controllers/DetailViewController.swift
@@ -236,24 +236,22 @@ extension DetailViewController {
             }
             .store(in: &cancellables)

-        // CombineLatestを用いて、errorTitleとerrorMessageを結合してAlertControllerをpresentする
-        Publishers.CombineLatest(viewModel.$errorTitle, viewModel.$errorMessage)
-            .compactMap { title, message -> (String, String)? in
-                // nilじゃない値を持つ要素のみ抽出
-                guard let title, let message else { return nil }
-                return (title, message)
-            }
+        viewModel.$errorType
             .receive(on: DispatchQueue.main)
-            .sink { [weak self] title, message in
-                guard let self else { return }
-                self.presentErrorAlert(title: title, message: message)
+            .sink { [weak self] error in
+                guard let self, let error else { return }
+                self.presentErrorAlert(error: error)
             }
             .store(in: &cancellables)
     }

     /// エラーTitleとメッセージを表示
-    private func presentErrorAlert(title: String, message: String) {
-        let alert = UIAlertController(title: title, message: message, preferred
Style: .alert)
+    private func presentErrorAlert(error: ErrorType) {
+        let alert = UIAlertController(
+            title: error.errorTitle,
+            message: error.errorDescription,
+            preferredStyle: .alert
+        )
         alert.addAction(UIAlertAction(title: "確認", style: .default))
         present(alert, animated: true, completion: nil)
     }
diff --git a/CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailVie
wModel.swift b/CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailV
iewModel.swift
index a3ef9a9..7ca7a6e 100644
--- a/CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.
swift
+++ b/CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.
swift
@@ -20,10 +20,8 @@ final class DetailViewModel {
     @Published private(set) var isStarred: Bool = false
     /// 詳細画面で扱うリポジトリ
     @Published private(set) var repository: Repositories.Repository
-    /// エラーTitle
-    @Published private(set) var errorTitle: String? = nil
-    /// エラーメッセージ
-    @Published private(set) var errorMessage: String? = nil
+    /// エラータイプ
+    @Published private(set) var errorType: ErrorType? = nil

     /** initializerでリポジトリを持っておく
     - ViewModelにリポジトリデータを持っておき、データの加工をViewModel側で処理
するようにする
@@ -51,8 +49,7 @@ final class DetailViewModel {
                 self.isStarred.toggle()
             case let .failure(error):
                 guard let self else { return }
-                self.errorTitle = error.errorTitle
-                self.errorMessage = error.errorDescription
+                self.errorType = error
             }
         }
     }
```

結果こんな感じになります。

https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/assets/39939005/e5eaf041-9f6f-4e5e-9344-770659e034fc

2024-06-17 10:08 UTC, KyusokLee commented on CodeAssignment_MVVM_Combine/Sources/ViewModels/DetailView/DetailViewModel.swift
> +    @Published private(set) var errorMessage: String? = nil
なるほど、、最初から`ErrorType`の`Publisher`を作って処理する考えはできなかったです。勉強になりました！
[7f86599](https://github.com/KyusokLee/CodeAssignment_MVVM_Combine/pull/6/commits/7f86599eb2a487880d34aa9f4c5e25fbc109f03f)にてコード修正しました。ご確認お願いします！

2024-06-17 10:20 UTC, Ogijun2018 approved these changes

2024-06-17 10:20 UTC, merged